package ${packageName};

import ${importEntity};
import br.com.anteros.persistence.session.repository.SQLRepository;

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

public interface ${repositoryName} extends SQLRepository<${entityType}, Long> {

}
