package ${packageName};

import br.com.anteros.security.spring.ResourceSecured;
import br.com.anteros.security.spring.service.SQLServiceSecured;
import ${importEntity};

/**
*  Generated by Anteros Generator Maven Plugin at ${time}
**/

@ResourceSecured(resourceName = "${resourceName}", description = "${resourceDescription}")
public interface ${serviceName} extends SQLServiceSecured<${entityType}, Long> {

}
