package ${packageName};

import br.com.anteros.persistence.session.service.SQLService;
import ${importEntity};

/**
*  Generated by Anteros Maven Plugin at ${time}
**/

public interface ${serviceName} extends SQLService<${entityType}, Long> {

}
