package ${packageName};

import ${importEntity};
import ${importService};
import br.com.anteros.persistence.session.service.GenericSQLService;

/**
*  Generated by Anteros Maven Plugin at ${time}
**/

public class ${serviceNameImpl} extends GenericSQLService<${entityType}, Long> implements ${interfaceService} {

}
